name: Auto Update Car Prices

on:
  schedule:
    - cron: '0 18 * * *'  # 每日凌晨 2:00（台灣時間，UTC+8）
  workflow_dispatch:      # 手動觸發功能

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler to update car prices
        run: |
          python car_price_updater.py

      - name: Commit and push updated data.json
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data.json
          git commit -m 'Update car price data [auto]'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
